### ISSUE TITLE
Tower of Hera coloring issue

### ISSUE THREAD

**Issue by emerald000** [pickfifteen/lttp-tracker#10] opened 2017-10-19 01:45 UTC
Tower of Hera has a couple of issues regarding its chests/boss requirements.

`(Flute || (Gloves && Lamp)) && (Mirror || (Hookshot && Hammer))` let's you enter the Tower of Hera normally. You can skip the Lamp if you don't mind dark rooms. If you don't have the lamp or the fire rod, you are restricted to the first two item locations. If the Big Key is in either of those, you can go ahead and get all locations except the one in the basement and kill Moldorm. If it isn't, well too bad.

So if you can enter, you can get 0-2 items and Moldorm is possibly killable (assuming sword or hammer). Glitched entrance/kill if no lamp and no flute. If you have Lamp of Fire Rod, it becomes fully clearable (Glitched again if no lamp and no flute).

So here are some tracker setups that returns the wrong values:

Gloves + Mirror: Expected Glitched Possible. Currently Unavailable.
Gloves + Hookshot + Hammer: Expected Glitched Possible. Currently Glitched Available.
Flute + Mirror: Expected Possible. Currently Unavailable.

There's probably some other variations that return wrong values. It seems like the sword also matters for the chests availability, but it should only matter for Moldorm. You can get through the whole dungeon with only bombs.

**Comment by SeraphinEveles** [comment] 2017-10-19 05:16
I can confirm the G+M returns as unavailable. I assume this is because the logic would require traveling through a dark room to get there. 
F+M does return as unavailable, as I would assume it doesn't take bombs into account, and thinks you need some other kind of item to activate the switches.

**Comment by pickfifteen** [comment] 2017-10-29 15:56
Closing all logic issues due to complete rewrite in #16. If any still exist, please open a new issue.

**Closed by pickfifteen** 2017-10-29 15:56 UTC
